### ISSUE TITLE
Crashing on Julia 1.11-rc1

### ISSUE THREAD

**Issue by marcelo-g-simas** [JuliaTesting/TestReports.jl#121]
When I try to use TestReports.jl on Julia 1.11.0-rc1 (2024-06-25) I get a crash before any tests run. Here's what happens:

```julia
julia> using TestReports; TestReports.test("WesVAR")
[ Info: Testing WesVAR
ERROR: KeyError: key "REPL" not found
Stacktrace:
  [1] getindex
    @ ./dict.jl:477 [inlined]
  [2] Base.Precompilation.ExplicitEnv(envpath::String)
    @ Base.Precompilation ./precompilation.jl:201
  [3] Base.Precompilation.ExplicitEnv()
    @ Base.Precompilation ./precompilation.jl:29
  [4] precompilepkgs(pkgs::Vector{String}; internal_call::Bool, strict::Bool, warn_loaded::Bool, timing::Bool, _from_loading::Bool, configs::Pair{Cmd, Base.CacheFlags}, io::Base.TTY, fancyprint::Bool)
    @ Base.Precompilation ./precompilation.jl:367
  [5] _require(pkg::Base.PkgId, env::String)
    @ Base ./loading.jl:2377
  [6] __require_prelocked(uuidkey::Base.PkgId, env::String)
    @ Base ./loading.jl:2216
  [7] #invoke_in_world#3
    @ ./essentials.jl:1077 [inlined]
  [8] invoke_in_world
    @ ./essentials.jl:1074 [inlined]
  [9] _require_prelocked(uuidkey::Base.PkgId, env::String)
    @ Base ./loading.jl:2207
 [10] macro expansion
    @ ./loading.jl:2146 [inlined]
 [11] macro expansion
    @ ./lock.jl:273 [inlined]
 [12] __require(into::Module, mod::Symbol)
    @ Base ./loading.jl:2103
 [13] #invoke_in_world#3
    @ ./essentials.jl:1077 [inlined]
 [14] invoke_in_world
    @ ./essentials.jl:1074 [inlined]
 [15] require(into::Module, mod::Symbol)
    @ Base ./loading.jl:2096
ERROR: TestReports failed to generate the report.
See error log above.

```

**Comment by mharradon** [comment]
I'm also running into this issue.

**Comment by KristofferC** [comment]
TestReports.jl generates an invalid manifest. The issue is:

```toml
[[deps.Pkg]]
deps = ["Artifacts", "Dates", "Downloads", "FileWatching", "LibGit2", "Libdl", "Logging", "Markdown", "Printf", "Random", "SHA", "TOML", "Tar", "UUIDs", "p7zip_jll"]
uuid = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
version = "1.11.0"
weakdeps = ["REPL"]

    [deps.Pkg.extensions]
    REPLExt = "REPL"
```

If there is no `[[deps.REPL]]`  in the manifest this needs to be saved in "expanded form" (which includes the UUID) as this:

```toml
[[deps.Pkg]]
deps = ["Artifacts", "Dates", "Downloads", "FileWatching", "LibGit2", "Libdl", "Logging", "Markdown", "Printf", "Random", "SHA", "TOML", "Tar", "UUIDs", "p7zip_jll"]
path = "../../home/kc/JuliaPkgs/Pkg.jl"
uuid = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
version = "1.11.0"

    [deps.Pkg.extensions]
    REPLExt = "REPL"

    [deps.Pkg.weakdeps]
    REPL = "3fa0cd96-eef1-5676-8a61-b3b8758bbffb"
```

The Pkg project writer handles this but this package instead chooses to directly print the manifest dictionary which cirumvents that.
